//TODO mana pool and mana regen
/*
 *  Project: TestingElementalMaster
 *  Author: Dash 
 *  Date: Mar 11, 2026
 */
package game.ui.battle;

import game.types.AttackType;
import game.character.holder.CharacterHolder;
import game.battle.simulator.SimulateBattle;
import game.engine.DamageCalculator;
import game.ui.battle.engine.UIUpdater;
import game.ui.battle.engine.IconLoader;
import game.ui.battle.engine.DamageAnimation;

/**
 *
 * @author Dash
 */
public class BattlePanel extends javax.swing.JPanel {
    private CharacterHolder activeEnemy;
    private CharacterHolder player;
    private SimulateBattle simulator; // The Bridge
    /**
     * Creates new form BattlePanel
     */
    public BattlePanel(CharacterHolder player, CharacterHolder enemy) {
        this.player = player;
        this.activeEnemy = enemy;
        this.simulator = new SimulateBattle(); // Initialize logic
        
        initComponents(); // 1. Create the UI objects
        lblPlayerTakeDamage.setVisible(false); //blinking damage receive animation
        lblEnemyTakeDamage.setVisible(false); //
        setupIcons();    // 2. Load the images into those objects currently not working
        
        
        // 1. Setup UI labels with the actual data
        lblPlayerName.setText(player.getName() + " (" + player.getElementType() + ")");
        lblEnemyName.setText(enemy.getName() + " (" + enemy.getElementType() + ")");
        
        refreshStats(); //Show initial HP values for both player and enemy
        
        // Set up the JTextArea to look like a terminal
        txtAreaBattlePanel.setEditable(false);
        txtAreaBattlePanel.setLineWrap(true);
        txtAreaBattlePanel.setWrapStyleWord(true);

        
        // 3. Welcome Message
        logToPanel("A duel begins: " + player.getName() + " vs " + enemy.getName());
        logToPanel("Choose an attack!");
    }   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBattlePanel = new javax.swing.JLabel();
        lblVS = new javax.swing.JLabel();
        lblPlayerName = new javax.swing.JLabel();
        lblEnemyName = new javax.swing.JLabel();
        lblPlayerIcon = new javax.swing.JLabel();
        lblEnemyIcon = new javax.swing.JLabel();
        pnlActionsButton = new javax.swing.JPanel();
        btnNormal = new javax.swing.JButton();
        btnSkill1 = new javax.swing.JButton();
        btnSkill2 = new javax.swing.JButton();
        btnUltimate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaBattlePanel = new javax.swing.JTextArea();
        lblAttackTypes = new javax.swing.JLabel();
        lblPlayerHP = new javax.swing.JLabel();
        lblEnemyHP = new javax.swing.JLabel();
        progPlayerHPBar = new javax.swing.JProgressBar();
        jProgressBar2 = new javax.swing.JProgressBar();
        lblEnemyTakeDamage = new javax.swing.JLabel();
        lblPlayerTakeDamage = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1280, 960));
        setMinimumSize(new java.awt.Dimension(1280, 960));
        setPreferredSize(new java.awt.Dimension(1280, 960));

        lblBattlePanel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblBattlePanel.setText("BATTLE PANNEL");

        lblVS.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblVS.setForeground(new java.awt.Color(255, 0, 0));
        lblVS.setText("VS");

        lblPlayerName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlayerName.setText("PLAYER NAME");

        lblEnemyName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEnemyName.setText(" ENEMY NAME");
        lblEnemyName.setMaximumSize(new java.awt.Dimension(78, 16));
        lblEnemyName.setMinimumSize(new java.awt.Dimension(78, 16));
        lblEnemyName.setPreferredSize(new java.awt.Dimension(78, 16));

        lblPlayerIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlayerIcon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lblPlayerIcon.setMaximumSize(new java.awt.Dimension(512, 512));
        lblPlayerIcon.setMinimumSize(new java.awt.Dimension(512, 512));
        lblPlayerIcon.setPreferredSize(new java.awt.Dimension(192, 192));

        lblEnemyIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEnemyIcon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lblEnemyIcon.setMaximumSize(new java.awt.Dimension(192, 192));
        lblEnemyIcon.setMinimumSize(new java.awt.Dimension(192, 192));
        lblEnemyIcon.setPreferredSize(new java.awt.Dimension(192, 192));

        pnlActionsButton.setMaximumSize(new java.awt.Dimension(384, 64));
        pnlActionsButton.setMinimumSize(new java.awt.Dimension(384, 64));
        pnlActionsButton.setPreferredSize(new java.awt.Dimension(384, 64));
        pnlActionsButton.setLayout(new java.awt.GridLayout(1, 0));

        btnNormal.setText("Normal");
        btnNormal.addActionListener(this::btnNormalActionPerformed);
        pnlActionsButton.add(btnNormal);

        btnSkill1.setText("SKILL 1");
        btnSkill1.addActionListener(this::btnSkill1ActionPerformed);
        pnlActionsButton.add(btnSkill1);

        btnSkill2.setText("SKILL 2");
        btnSkill2.addActionListener(this::btnSkill2ActionPerformed);
        pnlActionsButton.add(btnSkill2);

        btnUltimate.setText("ULTIMATE");
        btnUltimate.addActionListener(this::btnUltimateActionPerformed);
        pnlActionsButton.add(btnUltimate);

        jScrollPane1.setMaximumSize(new java.awt.Dimension(512, 144));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(512, 144));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(512, 144));

        txtAreaBattlePanel.setColumns(25);
        txtAreaBattlePanel.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        txtAreaBattlePanel.setRows(10);
        txtAreaBattlePanel.setMargin(new java.awt.Insets(0, 0, 0, 0));
        txtAreaBattlePanel.setMaximumSize(new java.awt.Dimension(512, 144));
        txtAreaBattlePanel.setMinimumSize(new java.awt.Dimension(512, 144));
        jScrollPane1.setViewportView(txtAreaBattlePanel);

        lblAttackTypes.setText("Attack Types");

        lblPlayerHP.setText("Health: ");

        lblEnemyHP.setText("Health:");

        progPlayerHPBar.setForeground(new java.awt.Color(255, 0, 0));

        jProgressBar2.setForeground(new java.awt.Color(255, 0, 0));

        lblEnemyTakeDamage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEnemyTakeDamage.setForeground(new java.awt.Color(255, 0, 0));
        lblEnemyTakeDamage.setMaximumSize(new java.awt.Dimension(100, 16));
        lblEnemyTakeDamage.setMinimumSize(new java.awt.Dimension(100, 16));
        lblEnemyTakeDamage.setPreferredSize(new java.awt.Dimension(100, 16));

        lblPlayerTakeDamage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPlayerTakeDamage.setForeground(new java.awt.Color(255, 0, 0));
        lblPlayerTakeDamage.setMaximumSize(new java.awt.Dimension(100, 16));
        lblPlayerTakeDamage.setMinimumSize(new java.awt.Dimension(100, 16));
        lblPlayerTakeDamage.setPreferredSize(new java.awt.Dimension(100, 16));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(547, 547, 547)
                .addComponent(lblBattlePanel)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(265, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlActionsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(374, 374, 374))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblAttackTypes)
                        .addGap(609, 609, 609))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblPlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(133, 133, 133))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblPlayerHP, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(progPlayerHPBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblPlayerTakeDamage, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, Short.MAX_VALUE)
                                        .addComponent(lblPlayerIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(163, 163, 163)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(lblEnemyHP, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(301, 301, 301))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(62, 62, 62)
                                        .addComponent(lblEnemyName, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblEnemyTakeDamage, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblEnemyIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(202, 202, 202))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblVS)
                        .addGap(604, 604, 604))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblBattlePanel)
                .addGap(49, 49, 49)
                .addComponent(lblVS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlayerName)
                    .addComponent(lblEnemyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEnemyHP)
                            .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEnemyIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(progPlayerHPBar, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPlayerHP))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(lblEnemyTakeDamage, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblPlayerIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(lblPlayerTakeDamage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblAttackTypes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlActionsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNormalActionPerformed
        handleAttack(AttackType.NORMAL);
    }//GEN-LAST:event_btnNormalActionPerformed

    private void btnSkill1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkill1ActionPerformed
        handleAttack(AttackType.SKILL_1);
    }//GEN-LAST:event_btnSkill1ActionPerformed

    private void btnSkill2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkill2ActionPerformed
        handleAttack(AttackType.SKILL_2);
    }//GEN-LAST:event_btnSkill2ActionPerformed

    private void btnUltimateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimateActionPerformed
        handleAttack(AttackType.ULTIMATE);
    }//GEN-LAST:event_btnUltimateActionPerformed
    //Replaced the String parameter and method is now handleAttack
    private void handleAttack(AttackType type) {
        // 1. Calculate Damage using your existing engine
        double dmg = DamageCalculator.calculateDamage(player, activeEnemy, type);

        // 2. Apply Damage to the Object
        activeEnemy.takeDamage(dmg);

        // 3. Update the UI
        logToPanel(player.getName() + " used " + type + "!");
        logToPanel("Dealt " + (int)dmg + " damage!");
        DamageAnimation.showDamageAnimation(lblEnemyTakeDamage,lblEnemyIcon ,dmg);//method damage receive animation
        refreshStats();

        // 4. Check for Win or Enemy Counter
        if (!activeEnemy.isAlive()) {
            logToPanel("VICTORY! " + activeEnemy.getName() + " fainted.");
            endBattle();
        } else {
            startEnemyTurnTimer();
        }
    }
    
    private void startEnemyTurnTimer() {
        // 1. Disable buttons so the player can't attack twice!
        setButtonsEnabled(false);

        // 2. Create a timer (1.5 seconds delay)
        javax.swing.Timer enemyTimer = new javax.swing.Timer(1500, e -> {
            // Logic from your terminal simulator
            //TODO Attack randomizer
            AttackType enemyMove = AttackType.NORMAL; // You can add your random logic here later
            double dmg = DamageCalculator.calculateDamage(activeEnemy, player, enemyMove);

            // Update Backend
            player.takeDamage(dmg);

            // Update UI
            logToPanel(activeEnemy.getName() + " attacks with " + enemyMove + "!");
            logToPanel("You took " + (int)dmg + " damage.");
            DamageAnimation.showDamageAnimation(lblPlayerTakeDamage,lblPlayerIcon ,dmg);
            refreshStats();

            // 3. Check if player survived
            if (!player.isAlive()) {
                logToPanel("DEFEAT... You have fallen.");
                endBattle();
            } else {
                // Re-enable buttons for the player's next turn
                setButtonsEnabled(true);
                logToPanel("Your turn!");
            }
        });

        enemyTimer.setRepeats(false); // Only run once
        enemyTimer.start();
    }
    
    
    private void refreshStats() {
        // Utilizing the engine //TODO
        UIUpdater.refreshHealthBar(progPlayerHPBar, player);
        UIUpdater.refreshHealthBar(jProgressBar2, activeEnemy);

        lblPlayerHP.setText("HP: " + (int)player.getCurrentHealth() + "/" + (int)player.getHP().getMaxHP());
        lblEnemyHP.setText("HP: " + (int)activeEnemy.getCurrentHealth() + "/" + (int)activeEnemy.getHP().getMaxHP());
    }
    
    private void setupIcons() {
        // Player Icon
        System.out.println("Looking for: " + player.getIconPath());
        java.net.URL testURL = getClass().getResource(player.getIconPath());
        System.out.println("Found it? " + (testURL != null));
        
        lblPlayerIcon.setIcon(IconLoader.getScaledIcon(this, player.getIconPath(), 192));
        lblPlayerIcon.setText("");

        // Enemy Icon
        lblEnemyIcon.setIcon(IconLoader.getScaledIcon(this, activeEnemy.getIconPath(), 192));
        lblEnemyIcon.setText("");
    }
    //UpdateBarColor has been moved to UIUpdater.java and is now called updateHealthBar
    
    private void endBattle() {
        setButtonsEnabled(false);

        // Using your JOptionPane trick from earlier!
        String winner = player.isAlive() ? "Victory!" : "Defeat...";
        javax.swing.JOptionPane.showMessageDialog(this, "The battle is over: " + winner);

        // TODO: Add code here to switch back to your Main Menu or Map
}

    // Helper method to keep code clean
    private void setButtonsEnabled(boolean enabled) {//simulate toggling on after enemy turn
        btnNormal.setEnabled(enabled);
        btnSkill1.setEnabled(enabled);
        btnSkill2.setEnabled(enabled);
        btnUltimate.setEnabled(enabled);
    }
    
    private void logToPanel(String text) { //acting terminal
        int width = 25; 
        int padding = Math.max(0, (width - text.length()) / 2);

        StringBuilder centeredText = new StringBuilder();
        for (int i = 0; i < padding; i++) {
            centeredText.append(" ");
        }

        txtAreaBattlePanel.append(centeredText.toString() + text + "\n");

        // This moves the "cursor" to the very end of the text
        txtAreaBattlePanel.setCaretPosition(txtAreaBattlePanel.getDocument().getLength());
    }
    //showDamageAnimation method moved to DamageAnimation.java
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNormal;
    private javax.swing.JButton btnSkill1;
    private javax.swing.JButton btnSkill2;
    private javax.swing.JButton btnUltimate;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAttackTypes;
    private javax.swing.JLabel lblBattlePanel;
    private javax.swing.JLabel lblEnemyHP;
    private javax.swing.JLabel lblEnemyIcon;
    private javax.swing.JLabel lblEnemyName;
    private javax.swing.JLabel lblEnemyTakeDamage;
    private javax.swing.JLabel lblPlayerHP;
    private javax.swing.JLabel lblPlayerIcon;
    private javax.swing.JLabel lblPlayerName;
    private javax.swing.JLabel lblPlayerTakeDamage;
    private javax.swing.JLabel lblVS;
    private javax.swing.JPanel pnlActionsButton;
    private javax.swing.JProgressBar progPlayerHPBar;
    private javax.swing.JTextArea txtAreaBattlePanel;
    // End of variables declaration//GEN-END:variables
}
