//TODO mana pool and mana regen
/*
 *  Project: TestingElementalMaster
 *  Author: Dash 
 *  Date: Mar 11, 2026
 */
package game.ui.battle;

import game.types.AttackType;
import game.character.holder.CharacterHolder;
import game.battle.simulator.SimulateBattle;
import game.battle.simulator.SimulateManaCost;
import game.battle.simulator.TurnResult;
import game.ui.battle.engine.UIUpdater;
import game.ui.battle.engine.IconLoader;
import game.ui.battle.engine.DamageAnimation;
import game.ui.battle.engine.CombatLog;
/**
 *
 * @author Dash
 */
public class BattlePanel extends javax.swing.JPanel {
    private CharacterHolder activeEnemy;
    private CharacterHolder player;
    private CombatLog terminalLog;
    private SimulateBattle simulator; // The Bridge
    private int roundNumber = 1;
    /**
     * Creates new form BattlePanel
     */
    public BattlePanel(CharacterHolder player, CharacterHolder enemy) {
        this.player = player;
        this.activeEnemy = enemy;
        this.simulator = new SimulateBattle(); // Initialize logic
        
        initComponents(); // 1. Create the UI objects
        lblPlayerTakeDamage.setVisible(false); //blinking damage receive animation
        lblEnemyTakeDamage.setVisible(false); //
        setupIcons();    // 2. Load the images into those objects currently not working
        //manaRegen
        lblPlayerManaRegen.setVisible(false);
        lblEnemyManaRegen.setVisible(false);
        // 1. Setup UI labels with the actual data
        lblPlayerName.setText(player.getName() + " (" + player.getElementType() + ")");
        lblEnemyName.setText(enemy.getName() + " (" + enemy.getElementType() + ")");
        
        refreshStats(); //Show initial HP values for both player and enemy
        
        // Set up the txtAreaBattlePanel to look like a terminal
        txtAreaBattlePanel.setEditable(false);
        txtAreaBattlePanel.setLineWrap(true);
        txtAreaBattlePanel.setWrapStyleWord(true);

       this.terminalLog = new CombatLog(txtAreaBattlePanel);
       
       // 3. Welcome Message
       terminalLog.log("A duel begins: " + player.getName() + " vs " + enemy.getName());
       terminalLog.log("Choose an attack!");
        
    }   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBattlePanel = new javax.swing.JLabel();
        lblVS = new javax.swing.JLabel();
        lblPlayerName = new javax.swing.JLabel();
        lblEnemyName = new javax.swing.JLabel();
        lblPlayerIcon = new javax.swing.JLabel();
        lblEnemyIcon = new javax.swing.JLabel();
        pnlActionsButton = new javax.swing.JPanel();
        btnNormal = new javax.swing.JButton();
        btnSkill1 = new javax.swing.JButton();
        btnSkill2 = new javax.swing.JButton();
        btnUltimate = new javax.swing.JButton();
        terminalScrollPane = new javax.swing.JScrollPane();
        txtAreaBattlePanel = new javax.swing.JTextArea();
        lblAttackTypes = new javax.swing.JLabel();
        lblPlayerHP = new javax.swing.JLabel();
        lblEnemyHP = new javax.swing.JLabel();
        progPlayerHPBar = new javax.swing.JProgressBar();
        progEnemyHPBar = new javax.swing.JProgressBar();
        lblEnemyTakeDamage = new javax.swing.JLabel();
        lblPlayerTakeDamage = new javax.swing.JLabel();
        lblPlayerMana = new javax.swing.JLabel();
        progPlayerManaBar = new javax.swing.JProgressBar();
        lblEnemyMana = new javax.swing.JLabel();
        progEnemyManaBar = new javax.swing.JProgressBar();
        lblPlayerManaRegen = new javax.swing.JLabel();
        lblEnemyManaRegen = new javax.swing.JLabel();
        lblRoundNumber = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBattlePanel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblBattlePanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBattlePanel.setText("BATTLE PANNEL");
        lblBattlePanel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblBattlePanel.setMaximumSize(new java.awt.Dimension(200, 32));
        lblBattlePanel.setMinimumSize(new java.awt.Dimension(200, 32));
        lblBattlePanel.setPreferredSize(new java.awt.Dimension(200, 32));
        add(lblBattlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 272, 32));

        lblVS.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblVS.setForeground(new java.awt.Color(255, 0, 0));
        lblVS.setText("VS");
        lblVS.setMaximumSize(new java.awt.Dimension(32, 32));
        lblVS.setMinimumSize(new java.awt.Dimension(32, 32));
        lblVS.setPreferredSize(new java.awt.Dimension(32, 32));
        add(lblVS, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 105, -1, -1));

        lblPlayerName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlayerName.setText("PLAYER NAME");
        add(lblPlayerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 105, 300, -1));

        lblEnemyName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEnemyName.setText(" ENEMY NAME");
        lblEnemyName.setMaximumSize(new java.awt.Dimension(78, 16));
        lblEnemyName.setMinimumSize(new java.awt.Dimension(78, 16));
        lblEnemyName.setPreferredSize(new java.awt.Dimension(78, 16));
        add(lblEnemyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(752, 105, 300, -1));

        lblPlayerIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlayerIcon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lblPlayerIcon.setMaximumSize(new java.awt.Dimension(512, 512));
        lblPlayerIcon.setMinimumSize(new java.awt.Dimension(512, 512));
        lblPlayerIcon.setPreferredSize(new java.awt.Dimension(192, 192));
        add(lblPlayerIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 200, -1, -1));

        lblEnemyIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEnemyIcon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lblEnemyIcon.setMaximumSize(new java.awt.Dimension(192, 192));
        lblEnemyIcon.setMinimumSize(new java.awt.Dimension(192, 192));
        lblEnemyIcon.setPreferredSize(new java.awt.Dimension(192, 192));
        add(lblEnemyIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(804, 200, -1, -1));

        pnlActionsButton.setMaximumSize(new java.awt.Dimension(384, 64));
        pnlActionsButton.setMinimumSize(new java.awt.Dimension(384, 64));
        pnlActionsButton.setPreferredSize(new java.awt.Dimension(384, 64));
        pnlActionsButton.setLayout(new java.awt.GridLayout(1, 0));

        btnNormal.setText("Normal");
        btnNormal.addActionListener(this::btnNormalActionPerformed);
        pnlActionsButton.add(btnNormal);

        btnSkill1.setText("SKILL 1");
        btnSkill1.addActionListener(this::btnSkill1ActionPerformed);
        pnlActionsButton.add(btnSkill1);

        btnSkill2.setText("SKILL 2");
        btnSkill2.addActionListener(this::btnSkill2ActionPerformed);
        pnlActionsButton.add(btnSkill2);

        btnUltimate.setText("ULTIMATE");
        btnUltimate.addActionListener(this::btnUltimateActionPerformed);
        pnlActionsButton.add(btnUltimate);

        add(pnlActionsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 609, 512, -1));

        terminalScrollPane.setMaximumSize(new java.awt.Dimension(512, 144));
        terminalScrollPane.setMinimumSize(new java.awt.Dimension(512, 144));
        terminalScrollPane.setPreferredSize(new java.awt.Dimension(512, 144));

        txtAreaBattlePanel.setColumns(25);
        txtAreaBattlePanel.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        txtAreaBattlePanel.setRows(10);
        txtAreaBattlePanel.setMargin(new java.awt.Insets(0, 0, 0, 0));
        txtAreaBattlePanel.setMaximumSize(new java.awt.Dimension(512, 144));
        txtAreaBattlePanel.setMinimumSize(new java.awt.Dimension(512, 144));
        terminalScrollPane.setViewportView(txtAreaBattlePanel);

        add(terminalScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 443, -1, -1));

        lblAttackTypes.setText("Attack Types");
        add(lblAttackTypes, new org.netbeans.lib.awtextra.AbsoluteConstraints(603, 587, -1, -1));

        lblPlayerHP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlayerHP.setText("Health: ");
        lblPlayerHP.setMaximumSize(new java.awt.Dimension(100, 16));
        lblPlayerHP.setMinimumSize(new java.awt.Dimension(100, 16));
        lblPlayerHP.setPreferredSize(new java.awt.Dimension(100, 16));
        add(lblPlayerHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 145, 72, -1));

        lblEnemyHP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEnemyHP.setText("Health:");
        lblEnemyHP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEnemyHP.setMaximumSize(new java.awt.Dimension(100, 16));
        lblEnemyHP.setMinimumSize(new java.awt.Dimension(100, 16));
        lblEnemyHP.setPreferredSize(new java.awt.Dimension(100, 16));
        add(lblEnemyHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 145, 71, -1));

        progPlayerHPBar.setForeground(new java.awt.Color(255, 0, 0));
        progPlayerHPBar.setMaximumSize(new java.awt.Dimension(150, 16));
        progPlayerHPBar.setMinimumSize(new java.awt.Dimension(150, 16));
        progPlayerHPBar.setPreferredSize(new java.awt.Dimension(150, 16));
        add(progPlayerHPBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 145, -1, 16));

        progEnemyHPBar.setForeground(new java.awt.Color(255, 0, 0));
        progEnemyHPBar.setMaximumSize(new java.awt.Dimension(150, 16));
        progEnemyHPBar.setMinimumSize(new java.awt.Dimension(150, 16));
        progEnemyHPBar.setPreferredSize(new java.awt.Dimension(150, 4));
        add(progEnemyHPBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(833, 145, -1, 16));

        lblEnemyTakeDamage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEnemyTakeDamage.setForeground(new java.awt.Color(255, 0, 0));
        lblEnemyTakeDamage.setText("-damage");
        lblEnemyTakeDamage.setMaximumSize(new java.awt.Dimension(100, 16));
        lblEnemyTakeDamage.setMinimumSize(new java.awt.Dimension(100, 16));
        lblEnemyTakeDamage.setPreferredSize(new java.awt.Dimension(100, 16));
        add(lblEnemyTakeDamage, new org.netbeans.lib.awtextra.AbsoluteConstraints(716, 211, 70, 19));

        lblPlayerTakeDamage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPlayerTakeDamage.setForeground(new java.awt.Color(255, 0, 0));
        lblPlayerTakeDamage.setText("-damage");
        lblPlayerTakeDamage.setMaximumSize(new java.awt.Dimension(100, 16));
        lblPlayerTakeDamage.setMinimumSize(new java.awt.Dimension(100, 16));
        lblPlayerTakeDamage.setPreferredSize(new java.awt.Dimension(100, 16));
        add(lblPlayerTakeDamage, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 211, 78, -1));

        lblPlayerMana.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlayerMana.setText("Mana:");
        lblPlayerMana.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblPlayerMana.setMaximumSize(new java.awt.Dimension(100, 16));
        lblPlayerMana.setMinimumSize(new java.awt.Dimension(100, 16));
        lblPlayerMana.setPreferredSize(new java.awt.Dimension(100, 16));
        add(lblPlayerMana, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 176, -1, -1));

        progPlayerManaBar.setMaximumSize(new java.awt.Dimension(150, 16));
        progPlayerManaBar.setMinimumSize(new java.awt.Dimension(150, 16));
        progPlayerManaBar.setPreferredSize(new java.awt.Dimension(150, 16));
        add(progPlayerManaBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 176, -1, 16));

        lblEnemyMana.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEnemyMana.setText("Mana:");
        lblEnemyMana.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEnemyMana.setMaximumSize(new java.awt.Dimension(100, 16));
        lblEnemyMana.setMinimumSize(new java.awt.Dimension(100, 16));
        lblEnemyMana.setPreferredSize(new java.awt.Dimension(100, 16));
        add(lblEnemyMana, new org.netbeans.lib.awtextra.AbsoluteConstraints(735, 176, -1, -1));

        progEnemyManaBar.setMaximumSize(new java.awt.Dimension(150, 16));
        progEnemyManaBar.setMinimumSize(new java.awt.Dimension(150, 16));
        progEnemyManaBar.setPreferredSize(new java.awt.Dimension(150, 16));
        add(progEnemyManaBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(832, 176, -1, -1));

        lblPlayerManaRegen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPlayerManaRegen.setForeground(new java.awt.Color(0, 153, 255));
        lblPlayerManaRegen.setText("+manaRegen");
        lblPlayerManaRegen.setToolTipText("");
        lblPlayerManaRegen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblPlayerManaRegen.setMaximumSize(new java.awt.Dimension(100, 16));
        lblPlayerManaRegen.setMinimumSize(new java.awt.Dimension(100, 16));
        lblPlayerManaRegen.setPreferredSize(new java.awt.Dimension(100, 16));
        add(lblPlayerManaRegen, new org.netbeans.lib.awtextra.AbsoluteConstraints(576, 176, -1, -1));

        lblEnemyManaRegen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEnemyManaRegen.setForeground(new java.awt.Color(0, 153, 255));
        lblEnemyManaRegen.setText("+manaRegen");
        lblEnemyManaRegen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEnemyManaRegen.setMaximumSize(new java.awt.Dimension(100, 16));
        lblEnemyManaRegen.setMinimumSize(new java.awt.Dimension(100, 16));
        lblEnemyManaRegen.setPreferredSize(new java.awt.Dimension(100, 16));
        add(lblEnemyManaRegen, new org.netbeans.lib.awtextra.AbsoluteConstraints(1008, 176, -1, -1));

        lblRoundNumber.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblRoundNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRoundNumber.setText("Round #1");
        lblRoundNumber.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblRoundNumber.setMaximumSize(new java.awt.Dimension(200, 32));
        lblRoundNumber.setMinimumSize(new java.awt.Dimension(200, 32));
        lblRoundNumber.setPreferredSize(new java.awt.Dimension(200, 32));
        add(lblRoundNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 48, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNormalActionPerformed
        //handleAttack(AttackType.NORMAL); updated now that manaValidator Method exists
        manaValidator(0, AttackType.NORMAL);
    }//GEN-LAST:event_btnNormalActionPerformed

    private void btnSkill1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkill1ActionPerformed
        //handleAttack(AttackType.SKILL_1); 
        manaValidator(1, AttackType.SKILL_1);
    }//GEN-LAST:event_btnSkill1ActionPerformed

    private void btnSkill2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkill2ActionPerformed
        //handleAttack(AttackType.SKILL_2);
        manaValidator(2, AttackType.SKILL_2);
    }//GEN-LAST:event_btnSkill2ActionPerformed

    private void btnUltimateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimateActionPerformed
        //handleAttack(AttackType.ULTIMATE);
        manaValidator(3, AttackType.ULTIMATE);
    }//GEN-LAST:event_btnUltimateActionPerformed
    
    private void manaValidator(int choice, AttackType selectedAttack) {
        // 1. Double check (Safety)
        if (canAfford(choice, selectedAttack)) {

            // 2. Spend Mana in the backend
            // We use a temporary SimulateManaCost just to get the exact value to deduct
            SimulateManaCost costCheck = new SimulateManaCost(choice, player, selectedAttack);
            player.manaCost(costCheck.getManaNeeded());

            // 3. UI: Lock down to prevent spam-clicking
            setButtonsEnabled(false); 

            // 4. Proceed to the actual battle logic
            handleAttack(selectedAttack);
        }
    }
    
    
    //Replaced the String parameter and method is now handleAttack
    private void handleAttack(AttackType type) {
        // 1. Call the TurnResult.java
        TurnResult result = simulator.executePlayerTurn(player, activeEnemy, type);
        
        // 2. Dont forget to update the damage
        activeEnemy.takeDamage(result.getDamageDealt());
        
        // 3. Update the UI
        terminalLog.log(result.getDescription());
        terminalLog.log("Dealt " + (int)result.getDamageDealt() + " damage!");
        DamageAnimation.showDamageAnimation(lblEnemyTakeDamage,lblEnemyIcon ,result.getDamageDealt());
        refreshStats();

        // 4. Check for Win or Enemy Counter
        if (!activeEnemy.isAlive()) {
            terminalLog.log("VICTORY! " + activeEnemy.getName() + " fainted.");
            endBattle();
        } else {
            startEnemyTurnTimer();
        }
    }
    
    private void startEnemyTurnTimer() {//TODO implement the "Sweating Icon" ask DanInRed for details
        // 0. lblCharacterManaRegen disappears at enemy's turn
        manaRegenUpdate(false);
        // 1. Disable buttons so the player can't attack twice!
        setButtonsEnabled(false);
        
        // 2. Create a timer (1.5 seconds delay)
        javax.swing.Timer enemyTimer = new javax.swing.Timer(1500, e -> {
            // Logic from terminal simulator
            TurnResult result = simulator.executeEnemyTurn(activeEnemy, player);
            
            refreshStats();
            
            // Dont forget to update the damage
            player.takeDamage(result.getDamageDealt());
            // Update UI
            terminalLog.log(activeEnemy.getName() + " attacks with " + result.getAttackUsed() + "!");
            terminalLog.log("You took " + (int)result.getDamageDealt() + " damage.");
            DamageAnimation.showDamageAnimation(lblPlayerTakeDamage,lblPlayerIcon ,result.getDamageDealt());
            refreshStats();

            // 3. Check if player survived
            if (!player.isAlive()) {
                terminalLog.log("DEFEAT... You have fallen.");
                endBattle();
            } else {
                // Re-enable buttons for the player's next turn
                roundIncrement();           // Mana regeneration is triggered inside roundIncrement
                btnNormal.setEnabled(true); // Normal is always free
                updateActionButtons();      // This will selectively enable Skill1, Skill2, Ult
                terminalLog.log("Your turn!");
            }
        });

        enemyTimer.setRepeats(false); // Only run once
        enemyTimer.start();
    }
    
    private void manaRegen(javax.swing.JLabel mana, CharacterHolder character){
        mana.setText("+" + (int)character.getRegenRate());
        mana.setVisible(true);
    }
    private void manaRegenUpdate(boolean update){
        lblPlayerManaRegen.setVisible(update);
        lblEnemyManaRegen.setVisible(update);
    }
    
    private void roundIncrement(){
        roundNumber++;
        lblRoundNumber.setText("ROUND #" + this.roundNumber);
        
        player.getMana().regenerate();
        activeEnemy.getMana().regenerate();
    
        manaRegen(lblPlayerManaRegen, player);
        manaRegen(lblEnemyManaRegen, activeEnemy);
        refreshStats();
        updateActionButtons();
    }
    
    private void refreshStats() {//triggered every player or enemy turn
        // Utilizing the engine //TODO
        UIUpdater.refreshHealthBar(progPlayerHPBar, player);
        UIUpdater.refreshHealthBar(progEnemyHPBar, activeEnemy);
        UIUpdater.refreshManaBar(progPlayerManaBar, player);
        UIUpdater.refreshManaBar(progEnemyManaBar, activeEnemy); 
        lblPlayerHP.setText("HP: " + (int)player.getCurrentHealth() + "/" + (int)player.getHP().getMaxHP());
        lblEnemyHP.setText("HP: " + (int)activeEnemy.getCurrentHealth() + "/" + (int)activeEnemy.getHP().getMaxHP());
        lblPlayerMana.setText("Mana: " + (int)player.getCurrentMana() + "/" + (int)player.getMana().getMaxMana());
        lblEnemyMana.setText("Mana: " + (int)activeEnemy.getCurrentMana() + "/" + (int)activeEnemy.getMana().getMaxMana());
        // updateActionButtons(); called after startEnemyTurnTimer
    }
    
    private void setupIcons() {
        lblPlayerIcon.setIcon(IconLoader.getScaledIcon(player.getIconPath(), 192));
        lblEnemyIcon.setIcon(IconLoader.getScaledIcon(activeEnemy.getIconPath(), 192));
        
        lblPlayerIcon.setText("");
        lblEnemyIcon.setText("");
    }
    //UpdateBarColor has been moved to UIUpdater.java and is now called updateHealthBar
    
    private void endBattle() {
        setButtonsEnabled(false);

        // Using your JOptionPane trick from earlier!
        String winner = player.isAlive() ? "Victory!" : "Defeat...";
        javax.swing.JOptionPane.showMessageDialog(this, "The battle is over: " + winner);

        // TODO: Add code here to switch back to your Main Menu or Map
}

    // Helper method to keep code clean
    private void setButtonsEnabled(boolean enabled) {//simulate toggling on after enemy turn
        btnNormal.setEnabled(enabled);
        btnSkill1.setEnabled(enabled);
        btnSkill2.setEnabled(enabled);
        btnUltimate.setEnabled(enabled);
    }
    
    private void updateActionButtons() {
        // We check the mana cost for each skill via SimulateManaCost
        // Note: Normal attack (choice 0) is usually 0 mana, so it stays enabled.

        btnSkill1.setEnabled(canAfford(1, AttackType.SKILL_1));
        btnSkill2.setEnabled(canAfford(2, AttackType.SKILL_2));
        btnUltimate.setEnabled(canAfford(3, AttackType.ULTIMATE));
    }
    
    // Helper method to keep the logic clean
    private boolean canAfford(int choice, AttackType type) {
        SimulateManaCost check = new SimulateManaCost(choice, player, type);
        return check.isChoiceValid(choice, player, type);
    }
     
    //logToPanel moved to CombatLog.java in src.game.ui.battle.engine
    
    //showDamageAnimation method moved to DamageAnimation.java
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNormal;
    private javax.swing.JButton btnSkill1;
    private javax.swing.JButton btnSkill2;
    private javax.swing.JButton btnUltimate;
    private javax.swing.JLabel lblAttackTypes;
    private javax.swing.JLabel lblBattlePanel;
    private javax.swing.JLabel lblEnemyHP;
    private javax.swing.JLabel lblEnemyIcon;
    private javax.swing.JLabel lblEnemyMana;
    private javax.swing.JLabel lblEnemyManaRegen;
    private javax.swing.JLabel lblEnemyName;
    private javax.swing.JLabel lblEnemyTakeDamage;
    private javax.swing.JLabel lblPlayerHP;
    private javax.swing.JLabel lblPlayerIcon;
    private javax.swing.JLabel lblPlayerMana;
    private javax.swing.JLabel lblPlayerManaRegen;
    private javax.swing.JLabel lblPlayerName;
    private javax.swing.JLabel lblPlayerTakeDamage;
    private javax.swing.JLabel lblRoundNumber;
    private javax.swing.JLabel lblVS;
    private javax.swing.JPanel pnlActionsButton;
    private javax.swing.JProgressBar progEnemyHPBar;
    private javax.swing.JProgressBar progEnemyManaBar;
    private javax.swing.JProgressBar progPlayerHPBar;
    private javax.swing.JProgressBar progPlayerManaBar;
    private javax.swing.JScrollPane terminalScrollPane;
    private javax.swing.JTextArea txtAreaBattlePanel;
    // End of variables declaration//GEN-END:variables
}
