
/*
 *  Project: TestingElementalMaster
 *  Author: Dash 
 *  Date: Mar 11, 2026
 */
package game.ui.battle;

/**
 *
 * @author Dash
 */
public class ResultPanel extends javax.swing.JPanel {

    /**
     * Creates new form ResultPanel
     */
    public ResultPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblResultPanel = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1280, 960));
        setPreferredSize(new java.awt.Dimension(1280, 960));

        lblResultPanel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblResultPanel.setText("RESULT PANEL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(329, 329, 329)
                .addComponent(lblResultPanel)
                .addContainerGap(614, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblResultPanel)
                .addContainerGap(890, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblResultPanel;
    // End of variables declaration//GEN-END:variables
}
