
/*
 *  Project: TestingElementalMaster
 *  Author: Dash 
 *  Date: Mar 11, 2026
 */
package game.ui;

import game.ui.menu.MenuPanel;
import javax.swing.JFrame;
/**
 *
 * @author Dash
 */
public class GameWindow extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GameWindow.class.getName());

    /**
     * Creates new form GameWindow
     */
    public GameWindow() {
            // 1. Let NetBeans init the basics (Title bar, close operation, etc.)
        initComponents(); 

        // 2. Clear out the lblTitle NetBeans added so it doesn't stay in memory
        this.getContentPane().removeAll(); 

        // 3. Set the starting view
        setView(new game.ui.splash.SplashPanel());

        // 4. Final Frame adjustments
        this.pack();
        this.setLocationRelativeTo(null); 

        // 5. Transition to Menu
        this.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mousePressed(java.awt.event.MouseEvent e) {
                setView(new MenuPanel()); 
                removeMouseListener(this);
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 0, 255));
        lblTitle.setText("CHAOS ELEMENTALS - REUNITE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(349, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(209, 209, 209))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(lblTitle)
                .addContainerGap(646, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    public void setView(javax.swing.JPanel newPanel) {
        // 1. Clear everything
        this.getContentPane().removeAll();

        // 2. Force a clean layout for the new panel
        this.getContentPane().setLayout(new java.awt.BorderLayout());
        this.getContentPane().add(newPanel, java.awt.BorderLayout.CENTER);

        // 3. Re-render
        this.getContentPane().revalidate();
        this.getContentPane().repaint();
        
        // 4. Focus management (important for key listeners)
        newPanel.requestFocusInWindow();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
