
/*
 *  Project: TestingElementalMaster
 *  Author: Dash 
 *  Date: Mar 11, 2026
 */
package game.ui.splash;

/**
 *
 * @author Dash
 */
public class SplashPanel extends javax.swing.JPanel {

    /**
     * Creates new form SplashPanel
     */
    public SplashPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSplashPanel = new javax.swing.JLabel();
        lblChaosElementalsReunite = new javax.swing.JLabel();
        lblClickToContinue = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));

        lblSplashPanel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSplashPanel.setText("SPLASHPANEL");

        lblChaosElementalsReunite.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblChaosElementalsReunite.setText("CHAOS ELEMENTALS: REUNITE");
        lblChaosElementalsReunite.setToolTipText("");

        lblClickToContinue.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblClickToContinue.setText("[Click Anywhere to Continue]");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblSplashPanel)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblChaosElementalsReunite)
                .addGap(380, 380, 380))
            .addGroup(layout.createSequentialGroup()
                .addGap(484, 484, 484)
                .addComponent(lblClickToContinue)
                .addGap(485, 485, 485))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblSplashPanel)
                .addGap(229, 229, 229)
                .addComponent(lblChaosElementalsReunite)
                .addGap(106, 106, 106)
                .addComponent(lblClickToContinue)
                .addGap(0, 529, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblChaosElementalsReunite;
    private javax.swing.JLabel lblClickToContinue;
    private javax.swing.JLabel lblSplashPanel;
    // End of variables declaration//GEN-END:variables
}
